// <auto-generated />
using DashboardCovid.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DashboardCovid.Data.Migrations
{
    [DbContext(typeof(DashboardCovidContexto))]
    [Migration("20200517024428_CovidMigration")]
    partial class CovidMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("DashboardCovid.Data.Entidades.InfeccaoPaisEntidade", b =>
                {
                    b.Property<int>("InfeccaoPaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CasosConfirmados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mortes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pais")
                        .HasColumnType("TEXT");

                    b.Property<int>("Recuperados")
                        .HasColumnType("INTEGER");

                    b.HasKey("InfeccaoPaisId");

                    b.ToTable("Infeccoes");
                });
#pragma warning restore 612, 618
        }
    }
}
